ACMS-1137: Build own Acquia CMS Starter Kit.
acquia/acquia-cms-starterkit pull request #107
Opened 2023-07-20 12:47 UTC by rajeshreeputra

**Motivation**
Fixes #ACMS-1137

**Proposed changes**
Provide way to customer to build own starterkit.

**Alternatives considered**
NA

**Testing steps**
Follow from ticket.

2023-07-20 13:43 UTC, apathak18 commented on src/Cli.php
> +    $fileContent = array_merge($defaultStarterkits['starter_kits'] ?? [], $userDefinedStarterkits['starter_kits'] ?? []);
No need of null coalescing operator.

2023-07-20 13:44 UTC, apathak18 commented on src/Cli.php
> +    $fileContent = array_merge($defaultStarterkits['starter_kits'] ?? [], $userDefinedStarterkits['starter_kits'] ?? []);
we can simplify line#121 with below statement.
$starterKits = array_merge($defaultStarterkits, $userDefinedStarterkits);

2023-07-20 13:45 UTC, apathak18 commented on src/Cli.php
> +    return $fileContent;
Add one empty line above return statement and change return statement to return $starterKits['starter_kits'] ?? []

2023-07-21 03:29 UTC, rajeshreeputra commented on src/Cli.php
> +    $userDefinedStarterkits = $this->getAcquiaCmsFile($this->rootDirectory . '/acms.yml');
@apathak18 have you tested this using testing steps to understand the difference?

2023-07-21 03:33 UTC, rajeshreeputra commented on src/Cli.php
> +    $fileContent = array_merge($defaultStarterkits['starter_kits'] ?? [], $userDefinedStarterkits['starter_kits'] ?? []);
@apathak18 this is not possible not possible as both has the starter_kits as parent key, hence only one will be returned, you can try by updating the same, at your end.

> we can simplify line#121 with below statement. $starterKits = array_merge($defaultStarterkits, $userDefinedStarterkits);

2023-07-21 03:37 UTC, rajeshreeputra commented on src/Cli.php
> +    $fileContent = array_merge($defaultStarterkits['starter_kits'] ?? [], $userDefinedStarterkits['starter_kits'] ?? []);
When one of the file is missing it return nothing, which is not array and will return "Warning: Undefined array key 'starter_kits'", hence null coalescing operator is required.
> No need of null coalescing operator.

2023-07-21 03:47 UTC, rajeshreeputra commented on src/Cli.php
> +    return $fileContent;
Added newline before return.

2023-07-21 03:50 UTC, apathak18 commented on src/Cli.php
> +    $userDefinedStarterkits = $this->getAcquiaCmsFile($this->rootDirectory . '/acms.yml');
Thanks clear now

2023-07-21 03:55 UTC, apathak18 commented on src/Cli.php
> +    $userDefinedStarterkits = $this->getAcquiaCmsFile($this->rootDirectory . '/acms.yml');
@rajeshreeputra Line#122 will throw exception in CLI if acms.yml file isn't exists at root directory, can we add a condition whether file exists or not? then do further logic implementation on the basis of that.

2023-07-21 04:05 UTC, rajeshreeputra commented on src/Cli.php
> +    $userDefinedStarterkits = $this->getAcquiaCmsFile($this->rootDirectory . '/acms.yml');
it is already there see - https://github.com/acquia/acquia-cms-starterkit/pull/107/files#diff-2715e1365c87080f44dc9848449f6101a079ed8a60928677f487d52f41ec661eR107-R109

2023-07-21 04:10 UTC, apathak18 commented on src/Cli.php
> +    $userDefinedStarterkits = $this->getAcquiaCmsFile($this->rootDirectory . '/acms.yml');
<img width="699" alt="Screenshot 2023-07-21 at 9 39 47 AM" src="https://github.com/acquia/acquia-cms-starterkit/assets/106175376/fef81ffb-c554-4ebc-b329-9f07e844432e">

2023-07-21 04:21 UTC, rajeshreeputra commented on src/Cli.php
> +    $fileContent = array_merge($defaultStarterkits['starter_kits'] ?? [], $userDefinedStarterkits['starter_kits'] ?? []);
@apathak18 also update logic to remove the null coalescing operator, thanks!! 😊

2023-07-21 05:23 UTC, apathak18 approved these changes

2023-07-21 06:56 UTC, deepakmishra2 approved these changes
Looks good to me

2023-07-24 09:34 UTC, chandan-singh7929 approved these changes

2023-07-26 05:26 UTC, vishalkhode1 approved these changes

2023-07-26 05:31 UTC, vishalkhode1 requested changes

2023-07-26 05:31 UTC, vishalkhode1 commented on src/Cli.php
> +      $userDefinedStarterkits = $this->getAcquiaCmsFile($this->rootDirectory . '/acms.yml');
@rajeshreeputra We should look for file in `acms` folder of root directory.

2023-07-26 06:09 UTC, rajeshreeputra commented on src/Cli.php
> +      $userDefinedStarterkits = $this->getAcquiaCmsFile($this->rootDirectory . '/acms.yml');
As discussed will update location from root directory to root/acms/acms.yml.

2023-07-26 10:02 UTC, vishalkhode1 approved these changes

2023-07-26 10:54 UTC, merged