ACMS-1905: Track Acquia CMS starterkits in telemetry data.
acquia/acquia-cms-starterkit pull request #108
Opened 2023-07-21 11:48 UTC by rajeshreeputra

**Motivation**
Fixes #ACMS-1905

**Proposed changes**
Track Acquia CMS Starterkits in telemetry data.

**Alternatives considered**
NA

**Testing steps**
Follow from ticket.

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

2023-07-24 12:06 UTC, chandan-singh7929 approved these changes
LGTM

2023-07-25 07:46 UTC, apathak18 approved these changes

2023-07-26 05:33 UTC, vishalkhode1 requested changes

2023-07-26 05:33 UTC, vishalkhode1 commented on src/Helpers/Task/InstallTask.php
> +    $command = array_merge([
@rajeshreeputra Why are we setting values in state now ?

2023-07-26 06:08 UTC, rajeshreeputra commented on src/Helpers/Task/InstallTask.php
> +    $command = array_merge([
removed.

2023-07-28 12:02 UTC, vishalkhode1 approved these changes

2023-07-28 12:02 UTC, merged