ACMS-1903: Use local executable for drush and fallback to global.
acquia/acquia-cms-starterkit pull request #112
Opened 2023-07-25 07:03 UTC by rajeshreeputra

**Motivation**

Fixes #ACMS-1903

**Proposed changes**
Use local executable for drush and fallback to global.

**Alternatives considered**
NA

**Testing steps**
Follow from ticket.

2023-07-26 07:28 UTC, apathak18 approved these changes

2023-07-30 18:44 UTC, vishalkhode1 requested changes

2023-07-30 18:44 UTC, vishalkhode1 commented on src/Helpers/Process/Commands/Drush.php
> +    if (!empty(shell_exec(sprintf("which %s", escapeshellarg('./vendor/bin/drush'))))) {
@rajeshreeputra Let's avoid this. This first looks for command and then update it. We can do following.
We can update `getCommand()` method of `CommandBase.php` like following:
is_executable($this->getBaseCommand())
```suggestion
  if (!is_executable($this->getBaseCommand())) {
    // Use ExecutableFinder to look for command globally.
  }
```


and then in Drush.php we can do following :
```suggestion
  public function getBaseCommand(): string {
    return './vendor/bin/drush';
  }
```

2023-07-31 07:28 UTC, rajeshreeputra commented on src/Helpers/Process/Commands/Drush.php
> +    if (!empty(shell_exec(sprintf("which %s", escapeshellarg('./vendor/bin/drush'))))) {
updated

2023-07-31 09:11 UTC, vishalkhode1 approved these changes

2023-07-31 09:11 UTC, merged

2023-07-31 09:27 UTC, chandan-singh7929 commented on src/Helpers/Process/Commands/CommandBase.php
> +        $this->rootDir . '/vendor/bin',
I don't think this change is needed since you have already override in  `getBaseCommand()`

2023-07-31 13:44 UTC, vishalkhode1 commented on src/Helpers/Process/Commands/CommandBase.php
> +        $this->rootDir . '/vendor/bin',
@chandan-singh7929 This is needed for extra directory to search for. For ex: in composer, the method `getBaseCommand()` returns `composer`. So, ExecutableFinder() class search if `composer` command is present in globally i.e in `/usr/local/bin` path. If it doesn't found then we've added as fallback that find this command in your project's `/vendor/bin` directory. If the same doesn't exist in global.