ACMS-3963: D11 compatibility Acquia CMS Starterkit.
acquia/acquia-cms-starterkit pull request #155
Opened 2024-07-03 13:34 UTC by rajeshreeputra

**Motivation**
Fixes #[ACMS-3963](https://acquia.atlassian.net/browse/ACMS-3963)

**Proposed changes**
Drupal 11 compatibility of Acquia CMS Starterkit.

**Alternatives considered**
NA

**Testing steps**
Follow from ticket.

2024-07-05 07:51 UTC, chandan-singh7929 approved these changes

2024-07-09 12:10 UTC, vishalkhode1 requested changes

2024-07-09 12:10 UTC, vishalkhode1 commented on composer.json
> +    "minimum-stability": "dev",
@rajeshreeputra Let's revert this as this is not required at the moment. We can add this once Acquia CMS modules are D11 compatible or atleast when we have D11 compatible dev version. Same for `src/Http/Client/Github/AcquiaRecommendedClient.php`

2024-07-09 17:27 UTC, vishalkhode1 requested changes

2024-07-09 17:27 UTC, vishalkhode1 commented on composer.json
> +        "phpspec/prophecy-phpunit": "^2.1",
@rajeshreeputra What's the reason of making this change and same for below ? I don't see this is required. If not, then let's revert this (and same for below i.e `phpunit/phpunit`).

2024-07-11 18:11 UTC, merged