ACMS-1314: Headless starter kit - Ask question to use Next.js in headless starter kit wizard
acquia/acquia-cms-starterkit pull request #47
Opened 2022-08-09 10:52 UTC by rajeshreeputra

Fixes: ACMS-1314

2022-08-10 21:14 UTC, fiasco commented on acms/acms.yml
> +    question: "Do you want to use Next.js (yes/no) ?"
This is a misleading question because [the next module is a dependency](https://github.com/acquia/acquia_cms/blob/develop/modules/acquia_cms_headless/acquia_cms_headless.info.yml#L13) of the acquia_cms_headless module. Instead, we could ask: Would you like to preconfigure a next.js site?

2022-08-10 21:16 UTC, fiasco commented on acms/acms.yml
> +    default_value: "Headless Site"
@vishalkhode1 you may need to review if we can support site name. AFAIK, the Next.js starter kit relies on the app being called "Headless Site 1" and if it is not, then it makes it difficult to toggle and control the associated consumer.

2022-08-12 07:49 UTC, rajeshreeputra commented on acms/acms.yml
> +    default_value: "Headless Site"
@fiasco we are in process to update the logic of creating associated consumer please have look at this [PR](https://github.com/acquia/acquia_cms/pull/1204).

2022-08-12 07:55 UTC, rajeshreeputra commented on acms/acms.yml
> +    question: "Do you want to use Next.js (yes/no) ?"
updated question text

2022-08-16 07:11 UTC, chandan-singh7929 commented on acms/acms.yml
> +      Please copy and paste the environment varibles to .env.local file later.
@rajeshreeputra - This is not require, we are already showing this message as part of drush command if the `env-file` not given.

2022-08-16 07:12 UTC, chandan-singh7929 approved these changes
Overall changes looks good to me.

2022-08-16 18:08 UTC, vishalkhode1 requested changes

2022-08-16 18:08 UTC, vishalkhode1 commented on acms/acms.yml
> +      Please copy and paste the environment varibles to .env.local file later.
@rajeshreeputra Yes, as mentioned by @chandan-singh7929 we shouldn't display the message. I think we can skip complete warning message for this.

2022-08-16 18:08 UTC, vishalkhode1 commented on src/Helpers/Task/Steps/InitNextjsApp.php
> +  public function __construct(Drush $drush) {
@rajeshreeputra Let's now use DI, instead of directly accessing the class.
```suggestion
  public function __construct(ContainerInterface $container) {
    $this->drushCommand = $container->get(Drush::class);
  }
```

2022-08-16 22:10 UTC, fiasco commented on acms/acms.yml
> +    question: "Please provide the Site URL"
Agree that is much less ambiguous.

2022-08-16 22:18 UTC, fiasco commented on acms/acms.yml
> +      Please copy and paste the environment varibles to .env.local file later.
Could we omit/hide this question altogether? So long as we told the end users where to find this file, it shouldn't matter where its located as they'll likely need to move it into its place in the node app anyway.

I'm keen to limit questions in the wizard where possible to ensure the process can be as fast as possible.

The only time where I could see this being useful would be in a CI job where you'd want to pass the env file name to the starter kit command as an option since user prompting isn't possible in a CI job. I'm not sure if that scenario is supported in the starter kit but is why I mentioned this question could be hidden if it still had utility later.

2022-08-16 22:24 UTC, fiasco commented on src/Helpers/Task/Steps/InitNextjsApp.php
> +  public function __construct(Drush $drush) {
I thought the point of services and DI was so classes were not dependant on the service container?

2022-08-17 03:55 UTC, vishalkhode1 commented on src/Helpers/Task/Steps/InitNextjsApp.php
> +  public function __construct(Drush $drush) {
@fiasco Ahh correct. But I think that's how currently the symfony auto-wiring the service dependencies in our case i.e using the complete class namespace whereas it should be based on some unique name, similar to how Drupal allows to create/manage service objects. I've that in mind to look & improve this, across all places in our project. :)

2022-08-17 06:01 UTC, rajeshreeputra commented on acms/acms.yml
> +      The Site URL is not set. Site URL is set to 'http://localhost:3000'.
done

2022-08-17 06:01 UTC, rajeshreeputra commented on acms/acms.yml
> +    question: "Please provide the Site URL"
updated

2022-08-17 06:02 UTC, rajeshreeputra commented on src/Helpers/Task/Steps/InitNextjsApp.php
> +  public function __construct(Drush $drush) {
updated

2022-08-17 06:02 UTC, rajeshreeputra commented on acms/acms.yml
> +      Please copy and paste the environment varibles to .env.local file later.
removed warning message.

2022-08-17 12:12 UTC, vishalkhode1 approved these changes

2022-08-17 12:12 UTC, merged