ACMS-000: Update CI to run for all starter-kits
acquia/acquia-cms-starterkit pull request #48
Opened 2022-08-10 10:25 UTC by rajeshreeputra

2022-09-15 05:53 UTC, apathak18 commented on src/Helpers/InstallerQuestions.php
> +        // $question['skip_on_value'] = FALSE;
@rajeshreeputra 
Remove this line if it is not required

2022-09-15 05:57 UTC, apathak18 commented on src/Helpers/InstallerQuestions.php
> +    if (getenv($key)) {
@rajeshreeputra Can we go something like this?
$default_value = (get($key)) ? getenv($key) : $question['default_value'];

2022-09-15 05:58 UTC, apathak18 commented on src/Helpers/InstallerQuestions.php
>      return trim(PHPParser::parseEnvVars($defaultValue));
@rajeshreeputra Can we go something like this?
return trim(PHPParser::parseEnvVars($defaultValue ?? ''));

2022-09-15 05:59 UTC, apathak18 commented on src/Helpers/InstallerQuestions.php
>      return trim(PHPParser::parseEnvVars($defaultValue));
@rajeshreeputra Can we go something like this?
return trim(PHPParser::parseEnvVars($defaultValue ?? ''));

2022-09-15 06:02 UTC, apathak18 commented on src/Commands/AcmsInstallCommand.php
> +    $allQuestions = array_merge(array_merge($questions['questionMustAsk'], $questions['questionSkipped']), $questions['questionCanAsk']);
Why we are using array_merge function twice?
If we are getting all value in line#152 then didn't understand the implementation of line#153

2022-09-15 06:04 UTC, apathak18 requested changes
@rajeshreeputra Provided some suggestions.

2022-09-15 12:46 UTC, chandan-singh7929 approved these changes
Overall changes looks good to me, take a look for the comment from Ankit.

2022-09-15 12:47 UTC, chandan-singh7929 commented
@rajeshreeputra - Since we are not covered nextjs part, please get update the ticket acceptance criteria accordingly.

2022-09-16 05:21 UTC, rajeshreeputra commented on src/Commands/AcmsInstallCommand.php
> +    $allQuestions = array_merge(array_merge($questions['questionMustAsk'], $questions['questionSkipped']), $questions['questionCanAsk']);
Updated the logic all together

2022-09-16 07:10 UTC, apathak18 commented on src/Helpers/InstallerQuestions.php
>    }
@rajeshreeputra Can we do something like this? instead of separate function we can include one parameter and do a early return.
 public function getDefaultOrEnvValue(array $question, string $key = "", string $type = NULL): string {

    if($type == 'env'){
      $envVarValue = trim(PHPParser::parseEnvVars(getenv($key)));
      return $envVarValue;
    }
   
    return trim(PHPParser::parseEnvVars($envVarValue ?? $question['default_value']));
  }

2022-09-16 09:40 UTC, apathak18 commented on src/Helpers/InstallerQuestions.php
> +    return trim(PHPParser::parseEnvVars(!empty($envVarValue) ? $envVarValue : $defaultValue));
As per the discussion please make this change.
return $envVarValue ?: trim(PHPParser::parseEnvVars($question['default_value']));

2022-09-16 09:40 UTC, apathak18 commented on src/Helpers/InstallerQuestions.php
> +    $defaultValue = $question['default_value'] ?? '';
Remove this line

2022-09-16 11:24 UTC, apathak18 approved these changes
LGTM

2022-09-16 12:58 UTC, deepakmishra2 approved these changes
Overall changes after ankit's feedback looks good to me.

2022-09-26 13:36 UTC, vishalkhode1 requested changes

2022-09-26 13:36 UTC, vishalkhode1 commented on .github/workflows/acms.yml
> +      ORCA_VERSION: v3.18.0
@rajeshreeputra Please revert this.

2022-09-27 05:29 UTC, vishalkhode1 approved these changes

2022-09-27 05:29 UTC, merged