ACMS-1695: Cypress integration testing added.
acquia/acquia-cms-starterkit pull request #90
Opened 2023-04-10 04:14 UTC by apathak18

2023-04-11 09:34 UTC, chandan-singh7929 commented on tests/functional/cypress/support/commands.js
> +// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })
Missing new line.

2023-04-11 09:34 UTC, chandan-singh7929 commented on tests/functional/cypress/support/e2e.js
> +// require('./commands')
Missing new line.

2023-04-11 09:36 UTC, chandan-singh7929 approved these changes
Over all changes looks good to me, just quick question any reason to put directory name as `1-nextjs-site-testing`

2023-04-11 12:14 UTC, vishalkhode1 requested changes

2023-04-11 12:14 UTC, vishalkhode1 commented on tests/functional/cypress/support/e2e.js
> +// require('./commands')
+1

2023-04-11 12:14 UTC, vishalkhode1 commented on tests/functional/cypress/videos/home.cy.js.mp4
@apathak18 What's the purpose of this file ???

2023-04-11 12:14 UTC, vishalkhode1 commented on tests/functional/cypress/e2e/1-nextjs-site-testing/places.cy.js
> +				"link": "/place/office/boston-head-office"
@apathak18 Need proper indentation.

2023-04-11 12:14 UTC, vishalkhode1 commented on tests/functional/cypress/e2e/1-nextjs-site-testing/people.cy.js
> +		"Home",
@apathak18 Please indent code.

2023-04-11 13:05 UTC, apathak18 commented on tests/functional/cypress/videos/home.cy.js.mp4
Mandatory

2023-04-12 06:35 UTC, rajeshreeputra approved these changes
Overall changes looks good to me.

2023-04-12 06:35 UTC, rajeshreeputra commented on tests/functional/cypress/e2e/1-nextjs-site-testing/articles.cy.js
> +    cy.visit('http://localhost:3000/articles')
please update to `cy.visit('http://127.0.0.1:3000/articles')`

2023-04-12 06:35 UTC, rajeshreeputra commented on tests/functional/cypress/e2e/1-nextjs-site-testing/events.cy.js
> +    cy.visit('http://localhost:3000/events')
please update to `cy.visit('http://127.0.0.1:3000/events')` otherwise this will fail in CI.

2023-04-12 06:35 UTC, rajeshreeputra commented on tests/functional/cypress/e2e/1-nextjs-site-testing/home.cy.js
> +    cy.visit('http://localhost:3000/')
please update to `cy.visit('http://127.0.0.1:3000')` otherwise this will fail in CI.

2023-04-12 06:35 UTC, rajeshreeputra commented on tests/functional/cypress/e2e/1-nextjs-site-testing/people.cy.js
> +    cy.visit('http://localhost:3000/people')
please update to `cy.visit('http://127.0.0.1:3000/people')` otherwise this will fail in CI.

2023-04-12 06:35 UTC, rajeshreeputra commented on tests/functional/cypress/e2e/1-nextjs-site-testing/places.cy.js
> +    cy.visit('http://localhost:3000/places')
please update to `cy.visit('http://127.0.0.1:3000/places')` otherwise this will fail in CI.

2023-04-12 07:14 UTC, deepakmishra2 approved these changes

2023-04-12 08:35 UTC, merged