ACMS-1830: Use global executable and fallback to local binary for com…
acquia/acquia-cms-starterkit pull request #96
Opened 2023-06-05 12:51 UTC by deepakmishra2

…poser/drush etc.

2023-06-07 11:39 UTC, rajeshreeputra approved these changes
Changes looks good.

2023-06-14 05:39 UTC, vishalkhode1 requested changes

2023-06-14 05:39 UTC, vishalkhode1 commented on src/Helpers/Process/Commands/CommandBase.php
> +  protected $package = ['composer', 'drush'];
@deepakmishra2 What's the purpose of this ? We should not restrict this to drush/composer command. This should be done for all commands.

2023-06-14 05:39 UTC, vishalkhode1 commented on tests/packages_alter.yml
> +acquia/blt : ~
@deepakmishra2 We can revert as blt released.

2023-06-14 09:41 UTC, apathak18 commented on tests/packages_alter.yml
> +acquia/blt : ~
Reverted

2023-06-14 09:42 UTC, apathak18 commented on src/Helpers/Process/Commands/CommandBase.php
> +  protected $package = ['composer', 'drush'];
Done the changes

2023-06-15 17:19 UTC, vishalkhode1 approved these changes

2023-06-15 17:19 UTC, merged